# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8763c1d9a091c2b264f2434fba9b8f1b48cfde6f06f1c7a005d7107be6cd2d562671734e7ab61c5b7947b69cca4073bd04e7b34d7119c90cb1fafea6bec12ca

test:
  secret_key_base: 329e8c53063cc0de5ac45a163306181d99a418da69d667e6cd216145e030d1fe2b82b3ef5c48f20e03099a7f7a12832bd46b9d7f0bc63d9777810089e933c939

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
